### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by Helavi** [SondreNjaastad/node-red-contrib-bluelinky#26] opened 2021-03-12 12:13 UTC
Hello,
I am having trouble with the configuration node. It seems that it is not possible to get connection. Beneath the bluelink nodes I always have an "Error" message. Could it be caused by the current transition mode Hyundai's BlueLink App is in? A call to Hyunday servicedesk told me, that they are merging the two different accounts from BlueLink and Hyundai into one account. So at the moment it isn't possible to log into the App with my former BlueLink Account (created September 2020), I have to use the Hyundai Account link, even I cant login with these Account on the MyHyundai Webpage: https://owners.hyundaiusa.com/us/en/index.html. So the merge seems not to be completed yet.
I would be really happy, if somebody can help me.
Bettina

**Comment by PierreLevres** [comment] 2021-03-12 12:16
Are you in US or EU? 

Apart from the account migration, Kia and Hyundai Europe changed their authentication process. Kuvork (node-red-support-kuvork) had been updated and should work in EU.

**Comment by Helavi** [comment] 2021-03-12 12:18
I am in Europe. Thanks for the Kuvork hint, I will try it.

**Comment by Helavi** [comment] 2021-03-12 12:20
Unfortunately I can't install it, it leads to a conflict. Is it necessary to remove the node-red-contrib-bluelinky?

**Comment by PierreLevres** [comment] 2021-03-12 12:25
The conflict is probably because basically all of bluelinky is forked into Kuvork, so it uses the samen function names and codenames... After a backup of your flows, you could uninstall and then install kuvork.
In the config you will need to provide the brand of the car, since Kuvork supports both Hyundai and Kia, where Bluelinky only supports Hyundai.

**Comment by Helavi** [comment] 2021-03-12 12:52
Unfortunately I still get an error. Is there something special to know. I enter username, password, region, pin and vin like I do in the Bluelink App. I have no idea what's the problem. Where do I have to provide the brand of my car, you mentioned?

**Comment by PierreLevres** [comment] 2021-03-12 12:58
If you have installed node-red-contrib-kuvork version 0.0.20 then in the configuration of the bluelinky node you will find 'brand'.. In your case be sure to select Hyundai
<img width="657" alt="Screenshot 2021-03-12 at 13 54 16" src="https://user-images.githubusercontent.com/62832923/110942989-e8ae2200-833a-11eb-8383-3b71f1cb4dd5.png">

**Comment by Helavi** [comment] 2021-03-12 13:07
Obviously something went wrong with deleting bluelinky and installing kuvork. I don't know how to add a screenshot, but in node red on the left side, still a category bluelinky is shown, while on the right side under Node Help, the node-red-contrib-kuvork with 7 different nodes is shown. That's probably the reason why my configuration form doesn't have the Brand line.

**Comment by PierreLevres** [comment] 2021-03-12 13:22
It can be a hassle….  
You could try node-red-stop and then npm remove node-red-contrib-bluelinky from ~/.node-red
If that fails, just delete the directory ~/.node-red/node_modules/node-red-contrib-bluelinky 
Then again a node-red-start and see what happens in the palette manager…

**Comment by Helavi** [comment] 2021-03-12 14:45
Unfortunateley node-red-contrib-bluelinky isn't available any more. I now removed also the kuvork node, resetted the browser cache. After that finally the categorie bluelinky on the left side of red-node was empty (not fully removed). After that I installed kuvork new. Again on the left side the old bluelinky nodes are listed (9), while in the Node Help the kuvork nodes (7) with slightly different names are shown. BUT now the configuration form contains the Brand line - Juchuh!!!. But even now I don't succed in getting a connection. Still the error appears. I think I have to give up.

**Comment by raleeSheffield** [comment] 2021-03-12 15:02
If it helps, this is what my set up looks like - it works...

![NodeRed](https://user-images.githubusercontent.com/54179102/110957901-016f0580-8344-11eb-9260-f18141940ad5.PNG)

**Comment by Helavi** [comment] 2021-03-12 15:11
Thanks alot for your patience, it looks very the same like mine. So I assume, that maybe the login data are not valid. Do you use your Bluelink Account Logindata or do you have a myHyundai Account? What does the nodes on the right side, using the Node Help look like? Although 10 nodes are installed according to the info from the pallette, for me there are only 7 nodes shown in the Node Help. (Sorry, but I still don't know how to insert a screenshot)

**Comment by Helavi** [comment] 2021-03-12 15:17
Like you can see hopefully here, there are some points missing.
![2021-03-12 16_06_53-Window](https://user-images.githubusercontent.com/80523540/110959519-105ab580-834e-11eb-96c2-e86e67c179df.png)

**Comment by raleeSheffield** [comment] 2021-03-12 15:26
Hi,
I have a Kia, so the login details may be a bit different, but you just use the same ones you would use from the mobile App.  It almost looks like your version might not be the most recent as there were fewer nodes in earlier releases.
Rachel
PS I'm not the expert - that's Pierre, but I have managed to make it work!

**Comment by PierreLevres** [comment] 2021-03-12 15:34
It looks like you have an older version of Kuvork installed. In the palette manager, what version does it tell you have? It ought to be 0.0.20 with 10 nodes?  Apparently you are on a version prior to 0.0.16.
In the palette manager does it show " update "  next to Kuvork?
PS I am not an expert, just a copy-cat with minor adjustments :)

**Comment by Helavi** [comment] 2021-03-14 16:38
Sorry for late answer, I was out on the weekend. The installed version I had, was the 0.0.20. Now I have updated to 0.0.22, but nothing changed. Please see the screenshot how it looks like. On the left side there are 10 nodes, but on the right side there are only 7 nodes. 
![2021-03-14 17_34_47-Window](https://user-images.githubusercontent.com/80523540/111076285-04a4f580-84ec-11eb-9c7a-c8cbec673120.png)

**Comment by BertilJ** [comment] 2021-03-15 08:28
I'm in the same situation as @Helavi.

I've tried basically everything now (I'm running node-red as a add-on in HA).

- Uninstallning the npm package
- Removing the global configuration (i.e the actual credential data, this stays when just uninstallning the npm)
- Removing all Bluelink flows
- Uninstallning the whole add-on

But nothing really seems to get bluelinky to work. Any ideas on how to get a clearer error message out of the config node? Maybe that could get us further.

**Comment by Helavi** [comment] 2021-03-15 08:35
Hi BertilJ,
according to your 2. issue, how did you remove the global configuration with the credential data, which keep stored (where?) after uninstalling the bluelinky package?

**Comment by BertilJ** [comment] 2021-03-15 08:38
![image](https://user-images.githubusercontent.com/45094162/111125542-fef1f300-8571-11eb-958e-f4570073340a.png)

You should have it under the configuration nodes.

**Comment by PierreLevres** [comment] 2021-03-15 11:54
> I'm in the same situation as @Helavi.
> 
> I've tried basically everything now (I'm running node-red as a add-on in HA).
> 
> * Uninstallning the npm package
> * Removing the global configuration (i.e the actual credential data, this stays when just uninstallning the npm)
> * Removing all Bluelink flows
> * Uninstallning the whole add-on
> 
> But nothing really seems to get bluelinky to work. Any ideas on how to get a clearer error message out of the config node? Maybe that could get us further.

11 days ago BlueLinky 6.0.1 was released. The node-red-contrib-bluelinky settles for less. What version is bluelinky? (Run "npm version" from node_modules/bluelinky )

**Comment by BertilJ** [comment] 2021-03-15 13:59
> > I'm in the same situation as @Helavi.
> > I've tried basically everything now (I'm running node-red as a add-on in HA).
> > 
> > * Uninstallning the npm package
> > * Removing the global configuration (i.e the actual credential data, this stays when just uninstallning the npm)
> > * Removing all Bluelink flows
> > * Uninstallning the whole add-on
> > 
> > But nothing really seems to get bluelinky to work. Any ideas on how to get a clearer error message out of the config node? Maybe that could get us further.
> 
> 11 days ago BlueLinky 6.0.1 was released. The node-red-contrib-bluelinky settles for less. What version is bluelinky? (Run "npm version" from node_modules/bluelinky )

I will see if I can find a way to do this on the add-on. Are there any other ways to check the version directly from Node-red gui?

**Comment by Helavi** [comment] 2021-03-15 14:04
This is my result:
#pi@raspberrypi:~/.node-red/node_modules $ npm -v bluelinky
6.14.11
pi@raspberrypi:~/.node-red/node_modules $ npm -v kuvork
6.14.11
Strange that it seems to be higher numbered than it was release (according your comment)

**Comment by PierreLevres** [comment] 2021-03-15 14:47
That is the npm version... not the kuvork version.
That is why i asked for "npm version" from the kuvork directory. You ran "npm -v kuvork" 

This is my output:
pi@rpi:~/node_modules/kuvork $ {
>   kuvork: '6.2.2',
>   npm: '7.6.0',
>   node: '15.11.0',
>   v8: '8.6.395.17-node.27',
>   uv: '
> ^C
pi@rpi:~/node_modules/kuvork $ npm -v kuvork
7.6.0

**Comment by Helavi** [comment] 2021-03-15 14:54
Sorry...
pi@raspberrypi:~/.node-red/node_modules/kuvork $ npm version
{
  kuvork: '6.2.2',
  npm: '6.14.11',
  ares: '1.16.1',
  brotli: '1.0.9',
  cldr: '37.0',
  http_parser: '2.9.4',
  icu: '67.1',
  llhttp: '2.1.3',
  modules: '72',
  napi: '7',
  nghttp2: '1.41.0',
  node: '12.21.0',
  openssl: '1.1.1j',
  tz: '2019c',
  unicode: '13.0',
  uv: '1.40.0',
  v8: '7.8.279.23-node.45',
  zlib: '1.2.11

**Comment by PierreLevres** [comment] 2021-03-15 15:27
That is the right version. I don't know where you are running node-red from, but could you run that command in .node-red/node_modules/node-red-contrib-kuvork ? Does it say 'node-red-contrib-kuvork': '0.0.22'?
Could you run a "ls -lia" there?
And a ' cat bluelinky.html | grep "fullstatus" '

**Comment by Helavi** [comment] 2021-03-15 15:38
I am running node-red on a raspberry pi, as well as on a windows pc. Both machines show the same behaviour.
Yes, it is running version 0.0.22
  'node-red-contrib-kuvork': '0.0.22',
  npm: '6.14.11',
  ares: '1.16.1',
  brotli: '1.0.9',
  cldr: '37.0',
  http_p...

pi@raspberrypi:~/.node-red/node_modules/node-red-contrib-kuvork $ ls -lia
insgesamt 68
1416462 drwxr-xr-x   5 pi pi  4096 Mär 14 17:32 .
 268202 drwxr-xr-x 284 pi pi 12288 Mär 14 17:32 ..
1416465 -rw-r--r--   1 pi pi 13605 Okt 26  1985 bluelinky.html
1416638 -rw-r--r--   1 pi pi 10234 Okt 26  1985 bluelinky.js
1416736 drwxr-xr-x   3 pi pi  4096 Mär 14 17:32 .github
1416641 drwxr-xr-x   2 pi pi  4096 Mär 14 17:32 icons
1416636 drwxr-xr-x   3 pi pi  4096 Mär 14 17:32 .idea
1416562 -rw-r--r--   1 pi pi  1854 Mär 14 17:32 package.json
1416464 -rw-r--r--   1 pi pi   136 Okt 26  1985 .prettierrc
1416640 -rw-r--r--   1 pi pi   730 Okt 26  1985 README.md

And last but not least, the result from the cat command: 

__pi@raspberrypi:~/.node-red/node_modules/node-red-contrib-kuvork $ cat bluelinky.html|grep "fullstatus"
    RED.nodes.registerType('car-fullstatus', {
            return this.name || "car-fullstatus";
<script type="text/html" data-template-name="car-fullstatus">
<script type="text/html" data-help-name="car-fullstatus">__

**Comment by PierreLevres** [comment] 2021-03-15 15:56
All identical to my machine.. maybe some mixup with remaining parts of bluelinky? Either in node_modules/bluelinky or node_modules/node-red-contrib-bluelinky? You of course rebooted both machines to be sure?

**Comment by Helavi** [comment] 2021-03-15 16:15
Yes I rebooted both of course. I assume also there are some remaining parts of bluelinky, but I don't know where. There is no node_modules/bluelinky neither node_modules/node-red-contrib-bluelinky available any more.

**Comment by PierreLevres** [comment] 2021-03-15 16:49
I can see why you don't see the 3 other nodes on the right side, that is because de bluelinky.html doesn't contain the 'help' for those nodes. I fixed that in 0.0.23 , should be available in half an hour or so... but it won't add any functionality except for help.
What I don't see is why your node login fails... Maybe it is a credential thingie after all. Are the user accounts and passwords for your Kia/Hyundai account the same before and after upgrading?

**Comment by BertilJ** [comment] 2021-03-15 18:00
I logged out of the bluelink app to sign in again (to double check the PW I'm using).

Then I got this screen:

![image](https://user-images.githubusercontent.com/45094162/111199033-7e0e1800-85c0-11eb-8f40-c8cf71583c70.png)

Can that somehow been relate? My account is created after 9.12.20

**Comment by PierreLevres** [comment] 2021-03-15 18:34
Absoluty related. And the cause of  many authentication failures.

Make sure your upgraded / transitioned account has the same userid and password

**Comment by BertilJ** [comment] 2021-03-15 18:41
I created my Hyundai account directy, never had the Bluelink account, so that shouldn't be an issue for me then.

**Comment by Helavi** [comment] 2021-03-15 19:14
Thanks for the solving of the node number problem with version 0.0.23.

@BertilJ: As I learned from Hyundai service desk directly, there were 2 different accounts necessary for Bluelink and for MyHyunday. I only have one, the Bluelink Account, created in September 2020 and I had NO MyHyundai Account. Since about 2 weeks, I got the screen you showed above and had big problems with my Bluelink Account. According to the note (...created before 09.12.20) I used the first link and didn't succeed. Finally Hyunday service desk told me that I had to reset my Bluelink in the car. After that it worked, but Login was now only possible with the second Link (Hyundai Account), although I didn't had one. I could login into the App, but I still cannot Login into the MyHyundai Webpage with these Account data. Hyunday told me, that the Transition will be terminated by end of March. Maybe I can Login in April into MyHyunday. And maybe all these troubles causes the error message and it will work in April.

**Comment by BertilJ** [comment] 2021-03-16 08:09
> Thanks for the solving of the node number problem with version 0.0.23.
> 
> @BertilJ: As I learned from Hyundai service desk directly, there were 2 different accounts necessary for Bluelink and for MyHyunday. I only have one, the Bluelink Account, created in September 2020 and I had NO MyHyundai Account. Since about 2 weeks, I got the screen you showed above and had big problems with my Bluelink Account. According to the note (...created before 09.12.20) I used the first link and didn't succeed. Finally Hyunday service desk told me that I had to reset my Bluelink in the car. After that it worked, but Login was now only possible with the second Link (Hyundai Account), although I didn't had one. I could login into the App, but I still cannot Login into the MyHyundai Webpage with these Account data. Hyunday told me, that the Transition will be terminated by end of March. Maybe I can Login in April into MyHyunday. And maybe all these troubles causes the error message and it will work in April.

Good information, thanks. But then there isn't really anything similar for us regarding the account creation date, I picked up my car just after xmas and created the account at that point.

**Comment by Helavi** [comment] 2021-03-16 11:31
That are really very amazing and helpful informations, for me the same applies. With region canada I can login, but I get the same messages like BertilJ.

**Comment by PierreLevres** [comment] 2021-03-16 13:42
When you select Canada, a whole different set of API-calls is used. So that you get errors from those calls sounds logical.

What happens if you create a config.json in the bluelinky or kuvork directory, and from that directory run _LOG_LEVEL=debug node debug.js_  ?

config.json should contain

{
  "username": "myaddress@domain.tld",
  "password": "ComplexP!ssw0rd",
  "vin": "ABCD",
  "pin": "1234",
  "deviceUuid": "123456768",
  "brand": "K"
}

Brand is only necessary of you are on Kuvork, "K" for Kia, "H" for Hyundai

And then send lines here, after stripping personal information from those lines

**Comment by Helavi** [comment] 2021-03-16 17:55
Probably I did something wrong. I created an empty file config.json:
_pi@raspberrypi: /.node-red/node_modules/node-red-contrib-kuvork $ ls
bluelinky.html  bluelinky.js  **config.json**  icons  package.json  README.md
pi@raspberrypi:~/.node-red/node_modules/node-red-contrib-kuvork $ **LOG_LEVEL=debug node debug.js**

Here is the result:

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/home/pi/.node-red/node_modules/node-red-contrib-kuvork/debug.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}_

**Comment by PierreLevres** [comment] 2021-03-16 18:16
Put it in the kuvork directory. Not the node-red-contrib-kuvork directory

**Comment by Helavi** [comment] 2021-03-17 09:24
ok, sorry. But still not the expected result I guess:
pi@raspberrypi:~/.node-red/node_modules/kuvork $ LOG_LEVEL=debug node debug.js
internal/modules/cjs/loader.js:1044
    throw err;
    ^

SyntaxError: /home/pi/.node-red/node_modules/kuvork/config.json: Unexpected end       of JSON input
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1041:22)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/pi/.node-red/node_modules/kuvork/debug.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)

**Comment by PierreLevres** [comment] 2021-03-17 14:57
Indents in the config file?

**Comment by PierreLevres** [comment] 2021-03-17 18:54
> No, the created file is empty. I created it with touch config.json. After that I entered the command: LOG_LEVEL=debug node debug.js

You have to enter your credentials in the config.json 

See my example in a previous posting

**Comment by Helavi** [comment] 2021-03-17 19:08
Ok, I thought the system would fill it in with the in node-red configured data. So next question is, where do I get the deviceUuid?

**Comment by PierreLevres** [comment] 2021-03-17 21:32
That is not relevant unless you have multiple vehicles on your account. you can leave it blank “” I think.

**Comment by Helavi** [comment] 2021-03-17 21:44
Seems not to work

pi@raspberrypi:~/.node-red/node_modules/kuvork $ LOG_LEVEL=debug node debug.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'inquirer'
Require stack:
- /home/pi/.node-red/node_modules/kuvork/debug.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/pi/.node-red/node_modules/kuvork/debug.js:6:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/pi/.node-red/node_modules/kuvork/debug.js' ]
}

**Comment by PierreLevres** [comment] 2021-03-18 06:24
Seems like inquirer is not installed

in de kuvork directory run
npm i inquirer

**Comment by Hacksore** [comment] 2021-03-18 15:07
@Helavi 

If you don't have a MyHyundai account you should create one on https://owners.hyundaiusa.com/us/en/index.html and hit the register now?

This is the first I'm hearing this migration was going on in the US. I've always had a MyHundai account only, never a Bluelink one.

![image](https://user-images.githubusercontent.com/996134/111648322-3ad6c380-87d1-11eb-82bf-7e0151deb58a.png)

**Comment by Helavi** [comment] 2021-03-18 20:27
Finally a result, but does it mean?
pi@raspberrypi:~/.node-red/node_modules/kuvork $ LOG_LEVEL=debug node debug.js
? What Region are you in? EU
{ region: 'EU' }
Logging in...
[2021-03-18 21:25:03] debug: hebing@t-online.de
[2021-03-18 21:25:03] debug: H
[2021-03-18 21:25:03] debug: EU Controller created
[2021-03-18 21:25:03] debug: Bluelinky is logging in automatically, to disable use autoLogin: false
(node:25358) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Response code 400 (Bad Request)')
    at z.emit (events.js:303:17)
    at z.<anonymous> (/home/pi/.node-red/node_modules/kuvork/dist/index.js:17:170725)
    at Generator.throw (<anonymous>)
    at P (/home/pi/.node-red/node_modules/kuvork/dist/index.js:17:136)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:25358) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25358) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Helavi** [comment] 2021-03-18 20:31
@ Hacksore: I don't think it's useful to create a separate Hyunday Account additional to my existing Bluelink Account, since Hyundai told me, that the Bluelink Account will be also serve as a MyHyunday Account in future and that this transition will take until April. At the moment I cannot login into MyHyundai. I think I will wait until April and then try again if I can login into MyHyundai.

**Comment by PierreLevres** [comment] 2021-03-19 07:23
@Helavi I don't quite understand what you mean it wouldn't be useful to create that account. It would would certainly help in trying to fix the issue. A lots of login errors are related to the migration of the accounts.
If not, there is a new version of Kuvork released with more descriptive error messages. You could try that too. It generates all information needed to troubleshoot,
Kuvork will be deprecated soon, since Kia will be supported by Bluelinky too, thus eliminating the need for Kuvork.

**Comment by Helavi** [comment] 2021-03-19 10:41
I don't know where to create one, I can't find a webpage for the european region, only for usa, australia and uk.
And if I create now a new Hyunday Account, I will have 2 Accounts and I am afraid it will end in a mess, since as I understood, my Bluelink Account will in April be also a MyHyundai Account. Obviously its not possible at the moment to create an MyHyundai Account in Europe, or is there a link?

**Comment by PierreLevres** [comment] 2021-03-19 11:10
For me the transition took place when I logged off in the app, and tried to logon again. The system then asked for change (‘upgrade your account’).

**Comment by Hacksore** [comment] 2021-03-25 02:08
@Helavi see if the latest version work to resolve this issue.

**Comment by BertilJ** [comment] 2021-03-25 07:11
I've tested with the latest versions:

+ node-red-contrib-kuvork@0.0.23
+ bluelinky@7.0.0

Still the same issue, I'm running NodeRed under HA, so I'm not able to do the debug, but as soon as I got an hour to spare, I will setup an additional NR as standalone to test this and potentially debug.

**Comment by BertilJ** [comment] 2021-04-13 11:13
I'm still not able to login, so I've finally setup a PI with a clean install with NR.

No luck there either, still getting login errors. I'm running v 0.0.20 of Bluelinky.

But I'm not able to debug according to the instructions in the thread, there is no debug.js. Any guidelines on the debugging?

**Comment by PierreLevres** [comment] 2021-04-14 05:32
Are you following the discord conversation on this topic?
Since yesterday afternoon there is a solution. It is implemented in bluelinky 7.1.0. You have to manually update because node-red hasn’t been updated yet. So go to your node red directory in a terminal window and update: npm i bluelinky

**Comment by BertilJ** [comment] 2021-04-14 05:33
No, I don't. But I will try the solution directly.

Thanks

**Comment by BertilJ** [comment] 2021-04-14 05:45
Did a quick test and updated Bluelinky to 7.1.0 both on my HA install and on my now running stand alone installation and still same behaviour. I will see if I can find the discord coversation and see if that can give me any additional pointers.

**Comment by BertilJ** [comment] 2021-04-14 07:02
Fiddled around some and couldn't get it to work and needed to get the heating started in the car so I went in to the Bluelink-app.

Now the app didn't work and I tried to sign out and in again, got prompted to renew my PW and after that NR/Bluelinky does work for me as well.

I suggest that this is closed with solved in Bluelinky 7.1.0

**Comment by Hacksore** [comment] 2021-04-15 13:00
I'm closing this as "fixed" with `v0.0.21`, if it comes back a new issue should be opened up.

**Closed by Hacksore** 2021-04-15 13:00 UTC
